import Phaser from 'phaser';
import { isChapter02ProductionReviewMode } from './chapter-02-production-review-runtime.ts';

type SupportedTheme='meadow'|'moon'|'ruins'|'canyon'|'fortress';
const entry=(theme:SupportedTheme)=>({baseKey:`chapter-02-${theme}-base`,baseUrl:`/assets/production/battlefields/${theme}/battlefield-base.svg`,backgroundKey:`chapter-02-${theme}-background`,backgroundUrl:`/assets/production/battlefields/${theme}/background-landmarks.svg`,foregroundKey:`chapter-02-${theme}-foreground`,foregroundUrl:`/assets/production/battlefields/${theme}/foreground-low-density.svg`});
const BATTLEFIELDS:Readonly<Record<SupportedTheme,ReturnType<typeof entry>>>={meadow:entry('meadow'),moon:entry('moon'),ruins:entry('ruins'),canyon:entry('canyon'),fortress:entry('fortress')};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='meadow'||theme==='moon'||theme==='ruins'||theme==='canyon'||theme==='fortress'?theme:undefined;}
export function preloadChapter02ProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isChapter02ProductionReviewMode())return;for(const item of Object.values(BATTLEFIELDS)){for(const [key,url] of [[item.baseKey,item.baseUrl],[item.backgroundKey,item.backgroundUrl],[item.foregroundKey,item.foregroundUrl]] as const){if(!scene.textures.exists(key))scene.load.image(key,url);}}}
export function renderChapter02ProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isChapter02ProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const item=BATTLEFIELDS[theme];if(scene.textures.exists(item.baseKey))scene.add.image(640,360,item.baseKey).setDisplaySize(1280,720).setDepth(0);if(scene.textures.exists(item.backgroundKey))scene.add.image(640,360,item.backgroundKey).setDisplaySize(1280,720).setDepth(.4);if(scene.textures.exists(item.foregroundKey))scene.add.image(640,360,item.foregroundKey).setDisplaySize(1280,720).setDepth(2.4);}
