import Phaser from 'phaser';
import { isChapter03ProductionReviewMode } from './chapter-03-production-review-runtime.ts';

type SupportedTheme='golden'|'ruins'|'moon'|'fortress'|'canyon'|'burning';
const entry=(theme:SupportedTheme)=>({baseKey:`chapter-03-${theme}-base`,baseUrl:`/assets/production/battlefields/${theme}/battlefield-base.svg`,backgroundKey:`chapter-03-${theme}-background`,backgroundUrl:`/assets/production/battlefields/${theme}/background-landmarks.svg`,foregroundKey:`chapter-03-${theme}-foreground`,foregroundUrl:`/assets/production/battlefields/${theme}/foreground-low-density.svg`});
const BATTLEFIELDS:Readonly<Record<SupportedTheme,ReturnType<typeof entry>>>={golden:entry('golden'),ruins:entry('ruins'),moon:entry('moon'),fortress:entry('fortress'),canyon:entry('canyon'),burning:entry('burning')};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='golden'||theme==='ruins'||theme==='moon'||theme==='fortress'||theme==='canyon'||theme==='burning'?theme:undefined;}
export function preloadChapter03ProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isChapter03ProductionReviewMode())return;for(const item of Object.values(BATTLEFIELDS))for(const [key,url] of [[item.baseKey,item.baseUrl],[item.backgroundKey,item.backgroundUrl],[item.foregroundKey,item.foregroundUrl]] as const)if(!scene.textures.exists(key))scene.load.image(key,url);}
export function renderChapter03ProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isChapter03ProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const item=BATTLEFIELDS[theme];if(scene.textures.exists(item.baseKey))scene.add.image(640,360,item.baseKey).setDisplaySize(1280,720).setDepth(0);if(scene.textures.exists(item.backgroundKey))scene.add.image(640,360,item.backgroundKey).setDisplaySize(1280,720).setDepth(.4);if(scene.textures.exists(item.foregroundKey))scene.add.image(640,360,item.foregroundKey).setDisplaySize(1280,720).setDepth(2.4);}
