import Phaser from 'phaser';
import { isFifthSliceProductionReviewMode } from './fifth-slice-production-review-runtime.ts';

type SupportedTheme='burning'|'fortress'|'ruins'|'golden'|'meadow';
type Entry={readonly baseKey:string;readonly baseUrl:string;readonly backgroundKey:string;readonly backgroundUrl:string;readonly foregroundKey:string;readonly foregroundUrl:string;};
const make=(theme:SupportedTheme):Entry=>({baseKey:`fifth-slice-${theme}-base`,baseUrl:`/assets/production/battlefields/${theme}/battlefield-base.svg`,backgroundKey:`fifth-slice-${theme}-background`,backgroundUrl:`/assets/production/battlefields/${theme}/background-landmarks.svg`,foregroundKey:`fifth-slice-${theme}-foreground`,foregroundUrl:`/assets/production/battlefields/${theme}/foreground-low-density.svg`});
const BATTLEFIELDS:Readonly<Record<SupportedTheme,Entry>>={burning:make('burning'),fortress:make('fortress'),ruins:make('ruins'),golden:make('golden'),meadow:make('meadow')};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='burning'||theme==='fortress'||theme==='ruins'||theme==='golden'||theme==='meadow'?theme:undefined;}
export function preloadFifthSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isFifthSliceProductionReviewMode())return;for(const entry of Object.values(BATTLEFIELDS))for(const [key,url] of [[entry.baseKey,entry.baseUrl],[entry.backgroundKey,entry.backgroundUrl],[entry.foregroundKey,entry.foregroundUrl]] as const)if(!scene.textures.exists(key))scene.load.image(key,url);}
export function renderFifthSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isFifthSliceProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const e=BATTLEFIELDS[theme];if(scene.textures.exists(e.baseKey))scene.add.image(640,360,e.baseKey).setDisplaySize(1280,720).setDepth(0).setName(e.baseKey);if(scene.textures.exists(e.backgroundKey))scene.add.image(640,360,e.backgroundKey).setDisplaySize(1280,720).setDepth(.4).setName(e.backgroundKey);if(scene.textures.exists(e.foregroundKey))scene.add.image(640,360,e.foregroundKey).setDisplaySize(1280,720).setDepth(2.4).setName(e.foregroundKey);}
