import Phaser from 'phaser';
import { isSpecialContentProductionReviewMode } from './special-content-production-review-runtime.ts';

type SupportedTheme='meadow'|'golden'|'canyon'|'ruins'|'fortress'|'burning'|'moon';
const entry=(theme:SupportedTheme)=>({baseKey:`special-content-${theme}-base`,baseUrl:`/assets/production/battlefields/${theme}/battlefield-base.svg`,backgroundKey:`special-content-${theme}-background`,backgroundUrl:`/assets/production/battlefields/${theme}/background-landmarks.svg`,foregroundKey:`special-content-${theme}-foreground`,foregroundUrl:`/assets/production/battlefields/${theme}/foreground-low-density.svg`});
const BATTLEFIELDS:Readonly<Record<SupportedTheme,ReturnType<typeof entry>>>={meadow:entry('meadow'),golden:entry('golden'),canyon:entry('canyon'),ruins:entry('ruins'),fortress:entry('fortress'),burning:entry('burning'),moon:entry('moon')};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='meadow'||theme==='golden'||theme==='canyon'||theme==='ruins'||theme==='fortress'||theme==='burning'||theme==='moon'?theme:undefined;}
export function preloadSpecialContentProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isSpecialContentProductionReviewMode())return;for(const item of Object.values(BATTLEFIELDS))for(const [key,url] of [[item.baseKey,item.baseUrl],[item.backgroundKey,item.backgroundUrl],[item.foregroundKey,item.foregroundUrl]] as const)if(!scene.textures.exists(key))scene.load.image(key,url);}
export function renderSpecialContentProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isSpecialContentProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const item=BATTLEFIELDS[theme];if(scene.textures.exists(item.baseKey))scene.add.image(640,360,item.baseKey).setDisplaySize(1280,720).setDepth(0);if(scene.textures.exists(item.backgroundKey))scene.add.image(640,360,item.backgroundKey).setDisplaySize(1280,720).setDepth(.4);if(scene.textures.exists(item.foregroundKey))scene.add.image(640,360,item.foregroundKey).setDisplaySize(1280,720).setDepth(2.4);}
