import Phaser from 'phaser';
import { isThirdSliceProductionReviewMode } from './third-slice-production-review-runtime.ts';

type SupportedTheme='fortress'|'burning'|'canyon'|'moon'|'ruins';
const entry=(theme:string)=>({baseKey:`third-slice-${theme}-base`,baseUrl:`/assets/production/battlefields/${theme}/battlefield-base.svg`,backgroundKey:`third-slice-${theme}-background`,backgroundUrl:`/assets/production/battlefields/${theme}/background-landmarks.svg`,foregroundKey:`third-slice-${theme}-foreground`,foregroundUrl:`/assets/production/battlefields/${theme}/foreground-low-density.svg`});
const BATTLEFIELDS:Readonly<Record<SupportedTheme,ReturnType<typeof entry>>>={fortress:entry('fortress'),burning:entry('burning'),canyon:entry('canyon'),moon:entry('moon'),ruins:entry('ruins')};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='fortress'||theme==='burning'||theme==='canyon'||theme==='moon'||theme==='ruins'?theme:undefined;}
export function preloadThirdSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isThirdSliceProductionReviewMode())return;for(const item of Object.values(BATTLEFIELDS)){for(const [key,url] of [[item.baseKey,item.baseUrl],[item.backgroundKey,item.backgroundUrl],[item.foregroundKey,item.foregroundUrl]] as const){if(!scene.textures.exists(key))scene.load.image(key,url);}}}
export function renderThirdSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isThirdSliceProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const item=BATTLEFIELDS[theme];if(scene.textures.exists(item.baseKey))scene.add.image(640,360,item.baseKey).setDisplaySize(1280,720).setDepth(0);if(scene.textures.exists(item.backgroundKey))scene.add.image(640,360,item.backgroundKey).setDisplaySize(1280,720).setDepth(.4);if(scene.textures.exists(item.foregroundKey))scene.add.image(640,360,item.foregroundKey).setDisplaySize(1280,720).setDepth(2.4);}
