import Phaser from 'phaser';
import { isThirdSliceProductionReviewMode } from './third-slice-production-review-runtime.ts';

type SupportedTheme='fortress'|'burning'|'moon';
const BATTLEFIELDS:Readonly<Record<SupportedTheme,{readonly baseKey:string;readonly baseUrl:string;readonly backgroundKey:string;readonly backgroundUrl:string;readonly foregroundKey:string;readonly foregroundUrl:string;}>>={
  fortress:{baseKey:'third-slice-fortress-base',baseUrl:'/assets/production/battlefields/fortress/battlefield-base.svg',backgroundKey:'third-slice-fortress-background',backgroundUrl:'/assets/production/battlefields/fortress/background-landmarks.svg',foregroundKey:'third-slice-fortress-foreground',foregroundUrl:'/assets/production/battlefields/fortress/foreground-low-density.svg'},
  burning:{baseKey:'third-slice-burning-base',baseUrl:'/assets/production/battlefields/burning/battlefield-base.svg',backgroundKey:'third-slice-burning-background',backgroundUrl:'/assets/production/battlefields/burning/background-landmarks.svg',foregroundKey:'third-slice-burning-foreground',foregroundUrl:'/assets/production/battlefields/burning/foreground-low-density.svg'},
  moon:{baseKey:'third-slice-moon-base',baseUrl:'/assets/production/battlefields/moon/battlefield-base.svg',backgroundKey:'third-slice-moon-background',backgroundUrl:'/assets/production/battlefields/moon/background-landmarks.svg',foregroundKey:'third-slice-moon-foreground',foregroundUrl:'/assets/production/battlefields/moon/foreground-low-density.svg'},
};
function supportedTheme(scene:Phaser.Scene):SupportedTheme|undefined{const theme=(scene as unknown as{stage?:{theme?:string}}).stage?.theme;return theme==='fortress'||theme==='burning'||theme==='moon'?theme:undefined;}
export function preloadThirdSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isThirdSliceProductionReviewMode())return;for(const entry of Object.values(BATTLEFIELDS)){for(const [key,url] of [[entry.baseKey,entry.baseUrl],[entry.backgroundKey,entry.backgroundUrl],[entry.foregroundKey,entry.foregroundUrl]] as const){if(!scene.textures.exists(key))scene.load.image(key,url);}}}
export function renderThirdSliceProductionReviewBattlefields(scene:Phaser.Scene):void{if(!isThirdSliceProductionReviewMode())return;const theme=supportedTheme(scene);if(!theme)return;const entry=BATTLEFIELDS[theme];if(scene.textures.exists(entry.baseKey))scene.add.image(640,360,entry.baseKey).setDisplaySize(1280,720).setDepth(0);if(scene.textures.exists(entry.backgroundKey))scene.add.image(640,360,entry.backgroundKey).setDisplaySize(1280,720).setDepth(.4);if(scene.textures.exists(entry.foregroundKey))scene.add.image(640,360,entry.foregroundKey).setDisplaySize(1280,720).setDepth(2.4);}
